# Purpose:
# Author: Benedict Cummins-Mburu
# Last Updated: 5 Jun 2026
# Contact: b.cumminsmburu@utoronto.ca
# License: MIT

# --------- Setup ----------
library(tidyverse) # for data cleaning
library(arrow) # to save result as parquet
donations_data <- read_parquet("data/processed_data/donations_data.parquet")
PCFRF_2022 <- read_parquet("data/clean_data/clean_PCFRF_2022.parquet")

# ---- Pre-Processing ------
LOCAL_POLITICAL_ENTITIES <- c(
  "Registered associations",
  "Candidates"
)
VALID_FED_NAMES <- unique(PCFRF_2022$FED)

ELECTION_PERIODS <- list(
  `42` = list(start = as.Date("2015-08-02"), end = as.Date("2015-10-19")),
  `43` = list(start = as.Date("2019-09-11"), end = as.Date("2019-10-21")),
  `44` = list(start = as.Date("2021-08-15"), end = as.Date("2021-09-20"))
)
# TODO: replace above with `election_event` calls once this column can be trusted.
# TODO: in an Appendix in the paper, explicitly research and record the official writ periods. Above was generated by Claude.

# 1. Subset donations_data, only keeping local entity recipients
subsetted_data <- donations_data %>%
  filter(political_entity %in% LOCAL_POLITICAL_ENTITIES)

# 2. Pre-processing validation
if (all(!is.na(subsetted_data$recipient_district))) {
  message("Validation Passed.")
} else {
  stop("Validation Error: Some Local Political Entity FEDs are Missing.")
}
if (all(!is.na(subsetted_data$donor_district))) {
  message("Validation Passed.")
} else {
  stop("Validation Error: Some Local Political Entity FEDs are Missing.")
}
if (all(unique(subsetted_data$recipient_district) %in% VALID_FED_NAMES)) {
  message("Validation Passed.")
} else {
  stop("Validation Error: Some Recipient FEDs are Invalid.")
}
if (all(unique(subsetted_data$donor_district) %in% VALID_FED_NAMES)) {
  message("Validation Passed.")
} else {
  stop("Validation Error: Some Donor FEDs are Invalid.")
}

# 3. Define the election periods
subsetted_data <- subsetted_data %>%
  mutate(
    period = case_when(
      donation_date >= ELECTION_PERIODS[["42"]]$start &
        donation_date <= ELECTION_PERIODS[["42"]]$end ~ "42",
      donation_date >= ELECTION_PERIODS[["43"]]$start &
        donation_date <= ELECTION_PERIODS[["43"]]$end ~ "43",
      donation_date >= ELECTION_PERIODS[["44"]]$start &
        donation_date <= ELECTION_PERIODS[["44"]]$end ~ "44",
      .default = "off_cycle"
    )
  )

# -------- Execution --------

# Helper: summarise a filtered slice into sending/receiving + two edge columns
make_flow <- function(data, n_col, amt_col) {
  data %>%
    group_by(
      sending_district = donor_district,
      receiving_district = recipient_district
    ) %>%
    summarise(
      "{n_col}" := n(),
      "{amt_col}" := sum(amount_monetary, na.rm = TRUE),
      .groups = "drop"
    )
}

# 2a. Aggregate (all rows) — prune zero-donation edges, then build everything else
agg_flows <- make_flow(
  subsetted_data,
  n_col = "n_donations_all_both",
  amt_col = "donation_amount_all_both"
) %>%
  filter(n_donations_all_both > 0) # prune zero-donation edges here

# All subsequent joins start from agg_flows to inherit its pruned edge set
base_edges <- agg_flows %>%
  select(sending_district, receiving_district)

# Helper: left-join a summarised slice back onto the pruned edge set,
# filling missing combinations with 0
join_flow <- function(base, data, n_col, amt_col) {
  flow <- make_flow(data, n_col, amt_col)
  base %>%
    left_join(flow, by = c("sending_district", "receiving_district")) %>%
    mutate(
      across(all_of(c(n_col, amt_col)), ~ replace_na(.x, 0))
    )
}

# 2b. Off-cycle — EDAs only
eda_off <- subsetted_data %>%
  filter(political_entity == "Registered associations", period == "off_cycle")

base_edges <- join_flow(
  base_edges,
  eda_off,
  n_col = "n_donations_off_EDA",
  amt_col = "donation_amount_off_EDA"
)

# Helper to add a full on-cycle set (EDA / Candidate / Both) for a given period label
add_on_cycle_edges <- function(base, data, period_label) {
  eda <- data %>% filter(political_entity == "Registered associations")
  cand <- data %>% filter(political_entity == "Candidates")

  base %>%
    join_flow(
      eda,
      paste0("n_donations_", period_label, "_EDA"),
      paste0("donation_amount_", period_label, "_EDA")
    ) %>%
    join_flow(
      cand,
      paste0("n_donations_", period_label, "_candidate"),
      paste0("donation_amount_", period_label, "_candidate")
    ) %>%
    join_flow(
      data,
      paste0("n_donations_", period_label, "_both"),
      paste0("donation_amount_", period_label, "_both")
    )
}

# 2c. All on-cycle elections combined
on_all <- subsetted_data %>% filter(period != "off_cycle")
base_edges <- add_on_cycle_edges(base_edges, on_all, "on")

# 2d. Individual election cycles 42, 43, 44
for (cyc in c("42", "43", "44")) {
  cycle_data <- subsetted_data %>% filter(period == cyc)
  base_edges <- add_on_cycle_edges(base_edges, cycle_data, cyc)
}

# 2e. Attach aggregate columns and finalise
FED_OOD_data <- agg_flows %>%
  left_join(base_edges, by = c("sending_district", "receiving_district"))

# ---- Write to Parquet -----
write_parquet(FED_OOD_data, "data/processed_data/FED_donations_data.parquet")
