---
title: "Geolocating Political Donations in Canada"
author:
  - name: "Benedict Cummins-Mburu"
  - name: "Rohan Alexander"
    email: "rohan.alexander@utoronto.ca"
    attributes: 
        corresponding: true
thanks: "Code and data are available at: [https://github.com/bennypk1/geolocating-political-donations](https://github.com/bennypk1/geolocating-political-donations)."
date: today
date-format: long
format: pdf
linestretch: 1.3
number-sections: true
bibliography: references.bib
link-citations: true
---

# Introduction

"Although political parties and candidates must disclose the names of their donors, use of those lists for any purpose is prohibited, so researchers cannot use them to identify the target population" [@garnett_lifeblood_2022]. However, [@garnett_where_2024] uses to geolocate donors anyways. Further in the paper they say: "Using the disclosed postal code of donors paired with census data, Carmichael & Hayes (2014) find that donors are more likely to live in wealthier neighborhoods. More recently, a pair of articles have analyzed Elections Canada’s administrative dataset, (which discloses the names of donors, the amounts they donated, and to whom) using predictive analytics to identify donor ethnicity (Besco and Tolley 2020) and gender (Tolley, Besco, and Sevi 2020)". Very confusing.

# Literature Review

## Political Donation, Participation, and Representation

In Canada (and many other Western democratic nations) federal representation is fundamentally geographical: a Member of Parliament (MP) supposedly represents the aggregate views of their constituents, that is, everyone who lives within the boundaries of their riding. By voting during a general election, the citizens of a given electoral district increase the likelihood that their incumbent MP votes, acts, looks, and thinks how they want them to. Normatively, the stratification of the population across spatial lines efficiently groups similar citizens. Paired with the equal weight of each vote, this ultimately results in an ideal representative democracy ; there is high congruence between what a legislator does, and what their constituents want [@bednar_political_2011].

Beyond voting, individual citizens often seek to increase their local representation by volunteering at a local electoral district association (EDA), advocating for their preferred party online, or financially supporting a candidate’s campaign [@bednar_political_2011 ; @baker_getting_2016 ; @garnett_where_2024].Since these necessitate (1) more resources (e.g. time, effort, or money), (2) indicate greater political interest, and (3) often have larger impacts on electoral outcomes relative to voting, political scientists classically argue that these constitute “higher forms” of political participation [@bednar_political_2011].

Among these, donations stand out as a useful unit for (1) understanding the motivations behind political participation and (2) assessing whether higher forms of political participation distort the dyadic relationship between constituents and their MP. Here, we discuss two reasons why. First, donations are spatiotemporally unconstrained, telling us exactly when and where citizens seek representation [@gimpel_check_2008 ; @garnett_where_2024]. While the voter can only seek representation within their district and during an election cycle, the donor can legally contribute to various political entities, whenever, and as often as they want, subject to annual and per-election limits [@gimpel_check_2008 ; @canada_annual_2026]. Second, donations are the primary means by which individuals extend their representation beyond district borders (termed “surrogate” representation by [@gimpel_check_2008]). Enabled by modern digital communication, individuals are increasingly motivated to finance national parties, or non-local candidates, in an attempt to be represented on ideological, partisan, or identity-based grounds [@gimpel_check_2008]. For example, a Green-party partisan may realize their local candidate will lose, and are perfectly content funding another Green candidate in a closer race somewhere else. Similarly, a Black candidate may appeal to Black donors across the country seeking identity-based representation. Given that individual donors are the presently largest source of campaign funding [@carmichael_political_nodate ; @garnett_where_2024], high rates of out-of-district donation are of particular concern, since they risk shifting the effective representational structure away from one-Legislator-one-district and towards one-Legislator-one-donor base.

## Political Donations in the Canadian Context: What has been done

Much research has been done to determine the socio-demographic characteristics of donors and candidates in Canada. Most notably, Garnett analyzed candidate-bound donations during the 2015, 2019, and 2021 general elections, finding that donors are much more likely to originate from older, wealthier, and better-educated districts [@carmichael_political_nodate ; @garnett_where_2024]. From 2004 to 2015, federal donation amount increased, particularly in Western Canada [@mcmahon_follow_2015]. Sevi compiled a dataset of demographic variables for all candidates who ran between 1867 to 2019, revealing, for example, that the share of women incumbents has increased [@sevi_who_2021].

Garnett et al. propose that donors donate for two reasons: political (i.e. for representational gain) and transactional [@garnett_lifeblood_2022] They find that political motivations are more prevalent overall, but especially among older and affluent donors who contributed larger sums. Transactional donations were more likely at the local level, while political donations were more likely at the national level [@garnett_lifeblood_2022].

When analyzing donor-recipient relationships, Canadian research has found that donors tend to donate more to candidates that they share aspects of their identity with [@tolley_who_2022 ; @besco_ethnic_2022]. Tolley et al. found that women donors are more likely to donate to women candidates [@tolley_who_2022], and Besco & Tolley found high rates of co-ethnic donation, particularly among South Asian donors [@besco_ethnic_2022]. More generally, South Asian political participation appears to be particularly heightened in Canada, relative to other ethnocultural groups [see @garnett_where_2024 and Bronsens, 2012]. Together with previous findings on donor motivation, these results the hypothesis that out-of-district donors in Canada are likely socially motivated, seeking individual-based representation.

Finaly, some work has been done assessing the impacts of political donation on representation. Among incumbent Legislators, voting behaviour is seemingly independent of the composition of their donor base [@peoples_impact_2008]. However, an older study found that local campaign donations during the 1993 and 1997 elections meaningfully affected the amount of votes a candidate receives [@eagles_effectiveness_2004].

## American Out-of-District Donations to U.S. Congrssional Representatives

We were unable to find a rigorous treatment of out-of-district donations during Canadian federal elections. By contrast, American scholars have explicitly addressed out-of-district donations and their impacts on legislative representation, catalyzed primarily by Gimpel et al.’s extensive treatment of individual out-of-district donations during 4 Congressional elections from 1994 – 2004 [@gimpel_check_2008]. They propose the existence of “donor districts” ; a small set of older, wealthy, well-educated, and urban districts wherein a large majority of out-of-district donations originate, destined to Republican and Democrat candidates alike [@gimpel_check_2008 ; @bramlett_political_2011]. We should notice that these socio-economic factors are the same drivers of donor output in general across North America [@gimpel_political_2006 ; @garnett_where_2024]. Over this time period, they also observed an increase in the proportion of non-local donations received by the average candidate, from around 50% in 1994 to nearly 70% in 2004 [@gimpel_check_2008]. More recent studies suggest that this and similar trends have continued past 2004 [@bramlett_political_2011 ; @baker_getting_2016 ; @canes-wrone_out--district_nodate]. Driven by the observation that the “closeness” of local races strongly predicted which districts received these non-local donations, Gimpel et al. argue that gaining a partisan advantage (and not seeking ideological or identity-based representation) is the primary motivation behind non-local donations [@gimpel_check_2008].

Follow-up American research has found that out-of-district campaign contributions affects the voting behaviour of Congressional representatives, thereby distorting the supposedly-dyadic relationship between a representative and their district. A study of the 2006-2010 Congressional elections revealed that the average House representative becomes less responsive to their constituencies’ ideological preferences with increasing out-of-district public funding [@baker_getting_2016]. Canes-Wrone & Miller further explore the 2006-2016 Congressional elections to show that House voting behaviour is indeed associated with the preferences of their nation donor base [@canes-wrone_out--district_nodate], contrasted against research finding that political action committees (U.S. equivalents to EDAs) do not affect roll call behaviour [@ansolabehere_why_2003]. Yet another study on Senatorial elections emphasizes the rivalrous relationship between constituents and out-of-district donors, experimentally showing that constituents who learned about outside donation expected their Senators to be less loyal to local interests [@nathan_donor_2025]. More generally, longitudinal analyses of out-of-state (and therefore out-of-district donations) during Senate elections echo many House findings [@sievert_out_2023 ; @jacobs_nationalization_2024 ; @keena_out--state_2024].

To an even greater extent than in Canada, individual donors are the primary source of funding for both U.S. campaigns and U.S. congressmen [@gimpel_check_2008 ; @baker_getting_2016]. This fact, paired with the many known effects of out-of-district donors on campaigns and representatives discussed above paint the picture that representatives “represent” little more than the whims of their national donor base.

# Appendix A: Background on Federal Donation Limits

The Canadian Elections Act imposes contribution limits on the following registered, federal political entities [see a full list of definitions at @canada_political_2026]: political parties, local electoral district associations (EDAs), candidates, party nomination contestants, and party leadership contestants [@canada_annual_2026]. Regulated expenses for any of the entities themselves cannot exceed specific values (determined on an annual basis, different for each riding. Leadership contestants are a notable excpetion, with no campaign spending limits. See @canada_expenses_2026). Notably, registered third paries are not contribution-limited by the Act [@canada_third_2026]. However, expenses relating to their activities are capped on a per-riding basis, similar to other political entities [@canada_expenses_2026]

Only Canadian citizens or permanent residents can make contributions [@canada_understanding_2026]. Any donor who contributed \$20 or more to any of the five federal political entities listed above must have their name recorded (but not reported to Elections Canada ; @canada_understanding_2026). Donors with contributions exceeding \$200 must also have their names and addresses recorded and reported to Elections Canada [@canada_understanding_2026]. Cash donations above \$20 are prohibited [@canada_understanding_2026].

+-------------------------------------------------------------------------------------------+-------------------------+
| Political Entity                                                                          | 2026 Annual Limit (CAD) |
+===========================================================================================+=========================+
| To each registered national party                                                         | 1,775                   |
+-------------------------------------------------------------------------------------------+-------------------------+
| In total, to all EDAs, nomination contestants, and candidates (for each registered party) | 1,775                   |
+-------------------------------------------------------------------------------------------+-------------------------+
| In total, to each independent or non-affiliated candidate                                 | 1,775                   |
+-------------------------------------------------------------------------------------------+-------------------------+

: 2026 Annual Limits on Individual Contributions, Loans, and Loan Guarantees (adapted from Elections Canada website)

| Politician            | Own-Campaign Contribution Limit |
|-----------------------|---------------------------------|
| Nomination Contestant | 2,775                           |
| Candidate             | 5,000                           |
| Leadership Contestant | 25,000                          |

: 2026 Special Cases for Politicians

**Other Info to put somewhere:**

- Electoral district boundaries are subject to change every 10 years, as required by the Constitution of Canada [@canada_redistribution_2025].

- Increases by \$25 each year

# Appendix B: Source to IJF

The raw donations dataset is from Elections Canada's "Open data on contributions" page (see @canada_open_2025), and was accessed for this study on May 5, 2026. This dataset represents all contribution reports filed by registered political entities (see Appendix A) from January 2004 to present [@canada_open_2025]. This is the exact data the IJF starts with.

Table B1 shows how each source column is cleaned and mapped by the IJF. Source data had 10,095,198 entries, while IJF had 8,095,810 entries.

IJF appended extra archived data from the site [see @canada_open_2025], covering donations to political entities and candidates from 1993 - 2004. These do not matter for our analysis, and were discarded.

In the raw data, 31,873 rows (0.3% of the total data) is not from Individual donors (Buisnesses, Corporations, Trade, Associations, Government, Unincorporated). These can immediately be ignored.

Donations were dated based on their posted "contribution received date". When this was not available, used "Fiscal / Election date".

+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Column Name (EC)                                                                               | Column Name (IJF)   | IJF Cleaning | Value Information                                                                                                                                                                         |
+================================================================================================+=====================+==============+===========================================================================================================================================================================================+
| Political Entity                                                                               | political_entity    | No changes   | Entity of recipient.                                                                                                                                                                      |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Recipient ID                                                                                   | N/A                 | N/A          | 34,054 unique IDs ; seemingly an ID for each unique recipient. This would be very useful to me if go to the trouble to show it's accurate.                                                |
|                                                                                                |                     |              |                                                                                                                                                                                           |
|                                                                                                |                     |              | IJF only has 13,387 unique `recipient` entries. What happened?                                                                                                                            |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Recipient ; Recipient last name ; Recipient first name ; Recipient middle initial              | recipient           | No changes   | Name of recipient                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Political Party of Recipient                                                                   | political_party     | No changes\* | Party of recipient. IJF made changes, but don't matter to us.                                                                                                                             |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Electoral District                                                                             | electoral_district  | No changes   | Electoral district of recipient.                                                                                                                                                          |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Electoral event                                                                                | electoral_event     | CHANGES      | "Annual" is the most common by far, followed by "Quarterly". "Annual" only captures "Registered associations" and "Registered parties". "Quarterly" only captures "Registered parties".   |
|                                                                                                |                     |              |                                                                                                                                                                                           |
|                                                                                                |                     |              | - IJF data has "0", "1" and "2" as electoral events, don't know why. Also added other events such as missing by-laws, not relevant though. They span multiple years and entities as well. |
|                                                                                                |                     |              | - I'm only using the three election cycles. But may need all of it within the 2013 - 2023 range.                                                                                          |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fiscal/Election date                                                                           | donation_date\*     |              | used if Contribution Recieved Date is not available                                                                                                                                       |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Contribution Recieved date                                                                     | donation_date       |              |                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Form ID ; Part Number of Return ; Financial Report ; Financial Report part                     | N/A                 | N/A          | Not important, can ignore.                                                                                                                                                                |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Contributor type                                                                               | donor_type          | No changes   | I'm only keeping Individuals. Others only represent 0.3% of the data anyways.                                                                                                             |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Contributor name ; Contributor last name ; Contributor first name ; Contributor middle initial | donor_full_name     | No changes   |                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Contributor City ; Contributor Province ; Contributor Postal code                              | donor_location      | No changes   |                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Monetary amount                                                                                | amount_monetary     | No changes   |                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Non-Monetary amount                                                                            | amount_non_monetary | No changes   |                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Contribution given through                                                                     | N/A                 | N/A          | is constant NA in source, can disregard.                                                                                                                                                  |
+------------------------------------------------------------------------------------------------+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Ask Martin**:

- Why are there 0, 1, and 2 in abundance as 'electoral_event'?

- Why are 2M rows missing? Checked: not a date issue.

- Why aren't you saving recipient ID? If two donors have same name I'm finished. I need this column.

- Confirm all the "no changes" above.

# Appendix C: IJF to Clean

**Cleaning Steps we can Definitely Do (on IJF data)**:

- Restrict `donation_date` to between 2013 and 2023

  - At this stage, check that the unique number of `electoral_district` is 338.

# References